# -*- coding: utf-8 -*-
"""02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lw5yNIaGOCVxsO6CH6bfUWs5vTWyuq5H
"""

import pandas as pd    

url = "https://gist.githubusercontent.com/tgcsantos/3bdb29eba6ce391e90df2b72205ba891/raw/22fa920e80c9fa209a9fccc8b52d74cc95d1599b/dados_imoveis.csv"
dados = pd.read_csv(url)

dados     # mostra todo o conteúdo

dados.info()            #mostra informações sobre os dados da tabela

dados["Valor"][0]     #mostra o primeiro conteúdo da coluna "Valor"

dados["Valor"][0].split()    #separa um objeto usando o espaço entre as strings como referência, criando uma array com strings

dados["Valor"].str.split()  #causa separação do Objeto "Valor". Precisa usar ".str" para converter um objeto em string

dados["Valor"].str.split(expand = True)  #organiza a array em uma tabela

dados["Valor"].str.split(expand = True)[2].unique()   #mostra os valores das strings da terceira coluna sem repetir

len(dados["Valor"].str.split(expand = True)[1].unique())   #mostra quantas índices não repetidos existem na segunda coluna

dados[["Moeda", "Valor_Moeda", "Tipo_Anuncio"]] = dados["Valor"].str.split(expand = True) #Cria mais três string no Objeto dados
dados

dados["Tipo_Anuncio"].isnull()  #mostra apenas os índices do objeto "Tipo_Anuncio" que não possuem nenhum valor

dados[dados["Tipo_Anuncio"].isnull()]  #mostra os valores do objeto "dados" em que os índices da coluna "Tipo_Anuncio" estão vazios

dados[dados["Tipo_Anuncio"].isnull()]["Tipo_Anuncio"].unique() #mostra os valores não repetidos do objeto "dados", em que os índices da coluna "Tipo_Anuncio" estão vazios

dados = dados[dados["Tipo_Anuncio"].isnull()] #dados recebe ele mesmo, mas apenas as linhas em que os índices da coluna "Tipo_Anuncio" estão vazios
dados

dados["Valor_Moeda"].str.replace(".","")        #troca os "pontos" por "espaço vazio"
dados["Valor_Moeda"] = dados["Valor_Moeda"].str.replace(".","").astype(float) #A coluna "Valor_Moeda" recebe ela mesma, mas sem pontos e convertida para float
dados.info()

dados

dados["Valor_Moeda"].mean()         #tira a média da coluna "Valor_Moeda"

dados["Valor_Moeda"].plot.hist(bins=50)     #mostra um histograma com 50 barras

dados.describe()        #mostra algumas informações sobre o objeto "dados", como quantidade, média, desvio padrão, valor mínimo...

pd.set_option('display.float_format', lambda x: '%.2f' % x)  #configura a visualização do Pandas para eliminar a notação cientifica
dados.describe(include = 'all')     #mostra insformações sobre todos os elementos do objeto 'dados'

dados[['Rua', 'Bairro', 'Cidade']].describe()