# -*- coding: utf-8 -*-
"""Pandas_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hUFtrXX7cHnVq1fQbU-zvNnysoia1Spp
"""

import pandas as pd    

url = "https://gist.githubusercontent.com/tgcsantos/3bdb29eba6ce391e90df2b72205ba891/raw/22fa920e80c9fa209a9fccc8b52d74cc95d1599b/dados_imoveis.csv"
dados = pd.read_csv(url)
dados.head()    #mostra apenas as cinco primeiras linhas

dados     # mostra todo o conteúdo

dados.sample(10) #mostra 10 linhas aleatóriamente

dados["Bairro"][3]    #imprime o conteudo da coluna X linha

dados.info()      #mostra informações sobre os valores do CSV

dados["Banheiros"].mean()     #retorna a média da coluna "Banheiros"

dados["Bairro"] == "Vila Mariana"     # retonar TRUE ou FALSE

(dados["Bairro"] == "Vila Mariana" ) * 1    # retorna 1 para ou 0

sum(dados["Bairro"] == "Vila Mariana")      # soma os campos verdadeiros

tem_imoveis = dados["Bairro"] == "Vila Mariana"   #recebe apenas os dados da coluna Bairro, como TRUE ou FALSE
tem_imoveis

dados[tem_imoveis]          #mostra apenas os valores com TRUE na coluna "Bairro"

imoveis_vila_mariana = dados[tem_imoveis]     #retorna somente as linhas que tem "Vila Mariana" como valor
imoveis_vila_mariana["Metragem"].mean()       #retorna a média de "Metragem" de todos os imóveis da "vila mariana"

n_bairros = dados["Bairro"].value_counts()        #retorna a quantidades de linhas com o mesmo "Bairro"
n_bairros.head(10).plot.bar()      #retorna uma gráfico em barras com os 10 primeiros valores

